### ISSUE TITLE
Open note externally does not work on Flatpak builds

### ISSUE THREAD

**Issue by CrO2Cl2** [TriliumNext/Notes#54]
### Trilium Version

0.63.5

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Zorin OS 17.1

### Description

Since I remember using Trilium on the flathub build, the "open note externally" feature has never worked. This is probably because of the permissions the flatpak has. 

If it is not possible to give the flatpak the permissions to use this feature, we should at least tell the user that this feature is not available for the flatpak, so that the user does not think that this is a problem on their side.

**Comment by pano9000** [comment]
I can confirm this happens locally with the v0.91.6 as well.
However I can see the following error being output in the console:

```
Error: EMFILE: too many open files, watch '/var/tmp/tmp-3-0VpaCASEYD3c-School schedule.html'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at watch (node:fs:2490:36)
    at createFsWatchInstance (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:126:16)
    at setFsWatchListener (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:171:19)
    at NodeFsHandler._watchWithNodeFs (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:325:22)
    at NodeFsHandler._handleFile (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:391:29)
    at NodeFsHandler._addToNodeFs (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:615:31)
    at file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/index.js:343:25
    at async Promise.all (index 0) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/var/tmp/tmp-3-0VpaCASEYD3c-School schedule.html',
  filename: '/var/tmp/tmp-3-0VpaCASEYD3c-School schedule.html'
}
Error: EMFILE: too many open files, watch '/var/tmp/tmp-3-0VpaCASEYD3c-School schedule.html'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at watch (node:fs:2490:36)
    at createFsWatchInstance (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:126:16)
    at setFsWatchListener (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:171:19)
    at NodeFsHandler._watchWithNodeFs (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:325:22)
    at NodeFsHandler._handleFile (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:391:29)
    at NodeFsHandler._addToNodeFs (file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/handler.js:615:31)
    at file:///app/lib/com.github.triliumnext.notes/resources/app.asar/node_modules/chokidar/esm/index.js:343:25
    at async Promise.all (index 0) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/var/tmp/tmp-3-0VpaCASEYD3c-School schedule.html',
  filename: '/var/tmp/tmp-3-0VpaCASEYD3c-School schedule.html'
}

```
and it being printed twice is not a copy/paste mistake :-)

**Comment by mattiklock** [comment]
FWIW, I have made "Open Note Externally" work on 0.63.7 by running it like so:

```
TMPDIR=$(mktemp -d)

flatpak run --filesystem=$TMPDIR --env=TMPDIR=$TMPDIR com.github.zadam.trilium 
```

**Comment by eliandoran** [comment]
Fixed in https://github.com/TriliumNext/Notes/commit/0f28bbb1be951e236f65b772585e5e3554b05ce9.
