### ISSUE TITLE
(Bug report)【A rather serious issue】 The notes are experiencing automatic snapshot recovery, and the edited content does not have any historical records.

### ISSUE THREAD

**Issue by nvcutrb** [TriliumNext/Notes#831]
### Description

After editing the current note, switch to another note first, and then switch back to find that the content of the note has returned to the way it was edited at the beginning, as if a snapshot has been restored.

### TriliumNext Version

v0.90.12

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 pro

**Comment by nvcutrb** [comment]
The entire application itself did not encounter any errors, and when switching notes, it seemed like the cache of edited content was lost and the information was not successfully saved. You can imagine if you have been working hard for over an hour, and the act of switching notes results in all content being lost and becoming blank.
整个应用本身并没有出现报错，在切换笔记时像是丢失了编辑内容的缓存，并没有成功保存信息。你可以想象一下如果辛苦的忙活了一个多小时，结果一个切换笔记的行为导致所有内容丢失，变成空白的样子。

**Comment by nvcutrb** [comment]
Moreover, it seems that the entire snapshot function does not take snapshots when switching to other notes or when not selected, and there is no way to manually take snapshots.

**Comment by Nriver** [comment]
1. Are you using only a web server, or a combination of server and clients?  
2. Providing more logs would be helpful for analysis.  
3. Consider using `forceSaveRevision`. Assign a shortcut to it to save revisions manually.

**Comment by nvcutrb** [comment]
We are using the Windows portable client
Can you take a look at this log?
[log.txt](https://github.com/user-attachments/files/18238280/log.txt)

**Comment by nvcutrb** [comment]
During the process of checking the logs, I found some other errors, so I decided to send all the logs.
[log2.txt](https://github.com/user-attachments/files/18238319/log2.txt)

**Comment by nvcutrb** [comment]
I hope it can help you solve the problem.

**Comment by eliandoran** [comment]
@nvcutrb , most likely you have run into a CKEditor (the text editor library we are using) failure. This issue is very hard to reproduce and we haven't been able to reproduce it yet, generally it happens when you copy-paste. The data loss is caused by the editor no longer providing us with the changes; there is a protection in place but it seems that for you it failed.

Also it seems to have a syntax highlighting widget, could you please get rid of it? TriliumNext includes built-in syntax highlight, any external module might interfere with it:

```
14:14:17.873 JS Error: Execution of JS note "SyntaxHighlightWidget 代码高亮组件" with ID NHy5HnUxu4fD failed with error: Load of script note "SyntaxHighlightWidget 代码高亮组件" (NHy5HnUxu4fD) failed with: BalloonEditor is not defined
Stack: Error
    at Object.y [as logError] (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:139076)
    at Object.h [as showAndLogError] (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:127992)
    at executeBundle (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:54234)
    at async Object.getWidgetBundlesByParent (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:55370)
```

The name of the note you need to remove is "SyntaxHighlightWidget 代码高亮组件". There's no guarantee it's the cause of error, but it should help us rule any external factors.

Let us know if you encounter this issue again.

**Comment by nvcutrb** [comment]
Okay, I'll disable this component first and use it for a while later.

> ，则很可能您遇到了 CKEditor（我们正在使用的文本编辑器库）故障。此问题很难重现，我们还无法重现它，通常发生在您复制粘贴时。数据丢失是由于编辑器不再向我们提供更改造成的;有一个保护措施，但对您来说似乎失败了。
> 
> 此外，它似乎有一个语法高亮小部件，您能去掉它吗？TriliumNext 包含内置的语法高亮，任何外部模块都可能干扰它：
> 
> ```
> 14:14:17.873 JS Error: Execution of JS note "SyntaxHighlightWidget 代码高亮组件" with ID NHy5HnUxu4fD failed with error: Load of script note "SyntaxHighlightWidget 代码高亮组件" (NHy5HnUxu4fD) failed with: BalloonEditor is not defined
> Stack: Error
>     at Object.y [as logError] (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:139076)
>     at Object.h [as showAndLogError] (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:127992)
>     at executeBundle (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:54234)
>     at async Object.getWidgetBundlesByParent (http://127.0.0.1:37840/assets/v0.90.12/app-dist/desktop.js:1:55370)
> ```
> 
> 您需要删除的注释的名称是 “SyntaxHighlightWidget 代码高亮组件”。不能保证这是错误的原因，但它应该可以帮助我们排除任何外部因素。
> 
> 如果您再次遇到此问题，请告诉我们。

**Comment by process** [comment]
Possible dupe of #454?

---
Is there a way to do a custom local build of `trilium-ckeditor5`? I got `npm run build:dist` running in that project, but when I copy the `dist/browser/index.js` to `libraries/ckeditor/ckeditor.js`, I get "CKEditor is not defined" in the console. I feel I might be missing something obvious.

My thought is that we could try to get a repro working with some additional logging in CKEditor, and then possibly find better ways of detecting this sort of case. I don't have a repro yet, but it seems that it would be progress even to have a "fake" repro where we induce in a crash in CKEditor to force this state.

**Comment by process** [comment]
It seems like there's a lot of mystery surrounding these incidents. I don't think I've been able to get a perfect reproduction yet.
In #454, the logs show a long period of time without backend requests occurring and the user says they were editing the note. Then the user switched to another note and requests started up again. This seems mysterious to me, since the CKEditor instance should be reused when switching to a new note (right?). In the problem that affected Trilium 0.58, IIRC, _all_ saves stopped after the editor crashed. I can fake-reproduce that case by having the `change:data` handler return immediately.
For these new problems, it seems like it could be a problem deeper within CKEditor? I don't want to make assumptions without more information.

I just opened a PR adding more logging. I'm interested in helping to solve this bug 😁 

---
I managed to get CKEditor building too. I'm doing `yarn run build` inside the `ckeditor5-build-trilium` package. With that, it's possible to add more logging and force crashes on the CKEditor side, by adding a `throw Error();` in places. I still haven't been able to reproduce these cases though: the watchdog recreates the editor if there's a crash.

**Comment by darachm** [comment]
I think I've got something similar with 0.91.6 running here in Firefox, hosted on a linux system, accessed via HTTP. Might have some clues?

It seemed mysterious, but I can now reliably trigger some kind of freeze by putting these 96 characters (or 93 and a newline, or 90 and two newlines !) into a note, so I'm literally pasting or typing in
`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1234567890123456`
and after each one I can see a "Frontend update data" console log in browser. Then on the 97th character (or 94th and a newline, or 91st and two newlines) the console just shuts up and stops reporting updating data. If I delete the last character I just put in it'll go back to reporting updates, but if I put in the 97th (or more) characters and let it sit for about a minute, then after a while the console log will report an Uncaught Error "rejected by browser". And I'll get some errors in the triliumnext notes logs like:
`JS Error: Uncaught error: Message: undefined, Line: undefined, Column: undefined, Error object: "rejected by browser", Stack: undefined
Stack: y@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:153732
6860/</u/<@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:90579
EventListener.handleEvent*u@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:90210
1987/<@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:39084
async*__webpack_require__.a@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:163977
1987@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:37452
__webpack_require__@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:163316
@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:167705
@http://mydomain.com/assets/v0.91.6/app-dist/desktop.js:1:167713`
(domains changed to protect the innocent).

In the browser console (Firefox), right at startup there is a few warnings about using HTTP, one about "image-style-configuration-definition-invalid ", and one right after "Creating new CKEditor" that reads:
`Source map error: Error: request failed with status 404
Stack in the worker:networkRequest@resource://devtools/client/shared/source-map-loader/utils/network-request.js:43:9

Resource URL: null
Source Map URL: ckeditor.js.map`
Related?

Can anyone else test this 97th character thing? Am I crazy?

It feels like that just adding too much body content is choking up something where CKEditor doesn't know what to do, or it's getting the browser and backend out of sync, or something just really weird. 

Come to think of it, everything was running fine until I just did an apt update and upgrade in another tmux pane, and midway through that it started bugging out. I rebooted everything to see if that'd fix it, but it didn't - maybe I corrupted a database with two version of SQLITE?

**Comment by darachm** [comment]
And just like that it's back to working just fine... I was away from it for a few hours, and am now connecting from on the same WiFi network (although still through a tailscale "tailnet").

I did notice however `404 GET /ckeditor.js.map` a few times in the logs, which comports with the browser warning during load re "ckeditor.js.map"
